### PR TITLE
Change the filetype `adpl` to `apdl`

### PR DESCRIPTION
**Pull request by PawkyPenguin**
Use correct filetype for the commentary feature. As far as I am aware,
`adpl` does not exist and was probably a typo.

### CODE REVIEW

**Comment by rgieseke** [comment]
Many thanks, but this is a mirror only which I maintain to have a Git mirror of the original repo (https://foicica.com/hg/textadept).

Patches and issues are handled on the Textadept mailing list: https://foicica.com/lists/

You can probably just send a link to https://patch-diff.githubusercontent.com/raw/rgieseke/textadept/pull/3.diff

If you don't feel like signing up I'm also happy to forward this to the list, just let me know.

**Comment by PawkyPenguin** [comment]
Ah sorry, I missed the project headline.
I'd be glad if you could forward this to the list. I stumbled on this Repo more accidentally than anything, so I probably won't have too much to add in the future ;)

**Comment by rgieseke** [comment]
Will do! Thanks for taking the time to report it!

**Comment by rgieseke** [comment]
Fixed in https://github.com/rgieseke/textadept/commit/be48a65883aa3e7013228192e0a8363714bdf532 and will be in the next version 9.6

**Pull request closed without merging**
